apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      team: devops
  template:
    metadata:
      labels:
        team: devops
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
