apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod
  labels:
    app: nginx
    team: devops
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
