apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      team: devops
  template:
    metadata:
      name: nginx-pod
      labels:
        team: devops
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
